<?php

function packagr_drupal_menu() {

	$items['packagr'] = array(
		'access callback'=>true,
		'page callback' => 'packagr_drupal_query'	
	);
	
	return $items;
}


function packagr_drupal_query() {
	$offset = 0;
	$limit = 10;

	$articles = db_select('node');
	$articles->join('users', 'u', 'node.uid = u.uid');
	$articles->fields('node',array('nid'));
	$articles->fields('u', array('name'));
//	$articles->condition('type', array('article','photo'), 'in');
	$articles->range($offset,$limit);
	$query = $articles->execute();
	
//	echo $articles;
	
//	->fetchAllKeyed();

	$results = array();
	while ($article = $query->fetchAssoc()) {
//		$article['link'] = url("node/" . $article['nid']);
		$node = node_load($article['nid']);
		
		
		$post = array(
			'title'=>$node->title,
			'content'=>$node->body['und'][0]['value'],
			'author'=>$article['name'],
			'link' => url('node/' . $node->nid),
			'type'=> $node->type,
			'pubDate'=>date('c',$node->created),
		);

		// get a list of all the fields
		$fields_info=field_info_instances("node",$node->type);
		//array_push($results,$fields_info);
		$fields = array();
		foreach ($fields_info as $field_name => $value) {
		  $field_info = field_info_field($field_name);
		  $type = $field_info['type'];
		  $fields[$field_name] = $type;
//		  echo "The type is $type, duh.";
		}
		
		$post['fields'] = $fields;
		
		// FIX THIS
		// find taxonomies (Tags, categories)
		//$post->tags = taxonomy_node_get_terms($node);

		// FIX THIS
		// Find all attached images, regardless of what field they're in
		$post['images'] = array();
		$post['tags'] = array();
		foreach ($fields as $field_name=>$type) {
			if ($type=='image') {
				if ($node->{$field_name}['und'][0]) {
					array_push($post['images'],file_create_url($node->{$field_name}['und'][0]['uri']));
				}
			}
			if ($type=='taxonomy_term_reference') {
				if ($node->{$field_name}['und'][0]) {
					foreach ($node->{$field_name}['und'][0][]
					array_push($post['tags'],$node->{field_name}['und'][0])
				}
			}
		}
		

		array_push($results,$post);
		array_push($results,$node);	
		
	
	}


	$final = array(
		'results'=>$results,
		'status'=>'ok',
	);

	header("Content-type: application/json");
	echo json_encode($final);


}